In [1]:
import torch

In [2]:
x = torch.empty(5,3)

In [3]:
x

tensor([[ 3.3133e-24,  4.5744e-41,  3.6909e-37],
        [ 0.0000e+00, -2.2788e-33,  4.5743e-41],
        [-2.2788e-33,  4.5743e-41, -2.2789e-33],
        [ 4.5743e-41, -2.4682e-33,  4.5743e-41],
        [-2.4683e-33,  4.5743e-41, -1.9147e-33]])

In [4]:
x = torch.rand(5, 3)

In [5]:
x

tensor([[0.3101, 0.9420, 0.9596],
        [0.2787, 0.1647, 0.4624],
        [0.5950, 0.9544, 0.2393],
        [0.3251, 0.7954, 0.9200],
        [0.4575, 0.8575, 0.8831]])

In [6]:
x= torch.zeros(5, 3, dtype=torch.long)

In [7]:
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [8]:
x = torch.tensor([5.5, 3])

In [9]:
x

tensor([5.5000, 3.0000])

In [10]:
x.shape

torch.Size([2])

In [11]:
x = x.new_ones(5, 3, dtype=torch.double) 

In [13]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [14]:
x = torch.randn_like(x, dtype=torch.float)

In [15]:
x

tensor([[ 0.6121, -0.1552, -0.0483],
        [ 0.6531,  0.3020, -0.4623],
        [ 1.1669,  1.3180,  0.1363],
        [-0.4769,  1.0389, -1.0188],
        [ 0.4156,  0.5820, -1.6692]])

In [18]:
x.size()

torch.Size([5, 3])

In [19]:
x.shape

torch.Size([5, 3])