Torch.Tensor is the central class of the package. If you set its attribute .requires_grad as True, it starts to track all operations on it. When you finish your computation you can call .backward() and have all the gradients computed automatically. The gradient for this tensor will be accumulated into .grad attribute.

To stop a tensor from tracking history, you can call .detach() to detach it from the computation history, and to prevent future computation from being tracked.

To prevent tracking history (and using memory), you can also wrap the code block in with torch.no_grad():. This can be particularly helpful when evaluating a model because the model may have trainable parameters with requires_grad=True, but for which we don’t need the gradients.

There’s one more class which is very important for autograd implementation - a Function.

Tensor and Function are interconnected and build up an acyclic graph, that encodes a complete history of computation. Each tensor has a .grad_fn attribute that references a Function that has created the Tensor (except for Tensors created by the user - their grad_fn is None).

If you want to compute the derivatives, you can call .backward() on a Tensor. If Tensor is a scalar (i.e. it holds a one element data), you don’t need to specify any arguments to backward(), however if it has more elements, you need to specify a gradient argument that is a tensor of matching shape.

In [37]:
import torch

In [38]:
x = torch.ones(2, 2, requires_grad=True)
print(x)

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)


In [ ]:
y = tor

In [3]:
y = x + 2
print(y)

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)


In [4]:
y.grad_fn

In [5]:
z = y * y * 3

In [6]:
out = z.mean()

In [7]:
print(z, out)

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>) tensor(27., grad_fn=<MeanBackward0>)


In [8]:
a = torch.randn(2, 2)
a = ((a * 3) / (a - 1))
print(a.requires_grad)
a.requires_grad_(True)
print(a.requires_grad)
b = (a * a).sum()
print(b.grad_fn)

False
True


In [9]:
out.backward()

In [10]:
print(x.grad)

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])


In [11]:
y.grad

/home/sheng/.virtualenvs/kaggle/lib/python3.6/site-packages/torch/tensor.py:746: UserWarning: The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad attribute won't be populated during autograd.backward(). If you indeed want the gradient for a non-leaf Tensor, use .retain_grad() on the non-leaf Tensor. If you access the non-leaf Tensor by mistake, make sure you access the leaf Tensor instead. See github.com/pytorch/pytorch/pull/30531 for more informations.
  warnings.warn("The .grad attribute of a Tensor that is not a leaf Tensor is being accessed. Its .grad "


In [14]:
y.retain_grad

<bound method Tensor.retain_grad of tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)>

In [18]:
z.retain_grad

<bound method Tensor.retain_grad of tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)>

In [19]:
x = torch.randn(3, requires_grad=True)

y = x * 2

In [20]:
y

tensor([-0.6857,  0.9599,  2.4892], grad_fn=<MulBackward0>)

In [22]:
y.backward()

RuntimeError: grad can be implicitly created only for scalar outputs

In [23]:
v = torch.tensor([0.1, 1.0, 0.0001], dtype=torch.float)
y.backward(v)

In [24]:
x.grad

tensor([2.0000e-01, 2.0000e+00, 2.0000e-04])

In [25]:
x

tensor([-0.3429,  0.4800,  1.2446], requires_grad=True)

In [26]:
v = torch.tensor([1, 1.0, 1], dtype=torch.float)
y.backward(v)

RuntimeError: Trying to backward through the graph a second time, but the buffers have already been freed. Specify retain_graph=True when calling backward the first time.

In [27]:
y.zero_grad()

AttributeError: 'Tensor' object has no attribute 'zero_grad'

In [28]:
x = torch.randn(3, requires_grad=True)

y = x * 2

In [29]:
v = torch.tensor([1, 1.0, 1], dtype=torch.float)
y.backward(v)

In [30]:
x.grad

tensor([2., 2., 2.])

In [31]:
x = torch.rand(1, requires_grad=True)

In [32]:
y = x * x + 2* x+1

In [33]:
y

tensor([1.4357], grad_fn=<AddBackward0>)

In [34]:
y.backward()

In [35]:
x.grad

tensor([2.3964])

In [36]:
x

tensor([0.1982], requires_grad=True)